// src/lib/components/GrowthChart.svelte
<script lang="ts">
	import { age, type Reference } from '$lib/references';
	import type { Measurement } from '$lib/types';
	import { Chart } from 'svelte-chartjs';
	import zoomPlugin from 'chartjs-plugin-zoom';
	import {
		Chart as ChartJS,
		Title,
		Tooltip,
		Legend,
		LineElement,
		CategoryScale,
		LinearScale,
		PointElement,
		ScatterController
	} from 'chart.js';

	ChartJS.register(
		Title,
		Tooltip,
		Legend,
		LineElement,
		CategoryScale,
		LinearScale,
		PointElement,
		ScatterController,
		zoomPlugin
	);

	let {
		measurements,
		reference,
		sex,
		birthDate,
		motherHeight,
		fatherHeight
	}: {
		measurements: Measurement[];
		reference?: Reference;
		sex?: String;
		birthDate?: Date;
		motherHeight?: Number;
		fatherHeight?: Number;
	} = $props();

	let data = $derived({
		datasets: [
			{
				label: 'Height',
				type: 'scatter',
				backgroundColor: 'black',
				data: measurements.map((m) => ({ x: age(birthDate, m.date), y: m.height }))
			}
		]
	});
	let options = {
		responsive: true,
		scales: {
			x: { min: 0, max: 18 },
			y: { min: 0 }
		},
		plugins: {
			zoom: {
				limits: {
					x: { min: 0, max: 25, minRange: 1 },
					y: { min: 0, max: 300, minRange: 5 }
				},
				zoom: {
					wheel: { enabled: true },
					pinch: { enabled: true },
					mode: 'xy'
				},
				pan: {
					enabled: true,
					mode: 'xy'
				}
			}
		}
	};
</script>

<Chart type="scatter" {data} {options} class="h-50 w-50" />

// src/components/GrowthChart.vue
<template>
  <ScatterChart v-if="options && chartData" :chartData="chartData" :options="options" />
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import { ScatterChart } from 'vue-chart-3'
import { Chart, registerables } from 'chart.js'
import zoomPlugin from 'chartjs-plugin-zoom'

Chart.register(...registerables, zoomPlugin)

export default defineComponent({
  components: { ScatterChart },
  props: {
    scatterData: {
      type: Array,
      default: () => { [] }
    },
    centileData: {
      type: Array,
      default: () => { [] }
    },
    options: {
      type: Object,
      default: () => {
        return {
          responsive: true,
          scales: {
            x: { min: 0, max: 18 },
            y: { min: 0 },
          },
          plugins: {
            zoom: {
              limits: {
                x: { min: 0, max: 25, minRange: 1 },
                y: { min: 0, max: 300, minRange: 5 },
              },
              zoom: {
                wheel: { enabled: true },
                pinch: { enabled: true },
                mode: 'xy',
              },
              pan: {
                enabled: true,
                mode: 'xy',
              },
            },
          },
        }
      },
    },
    color: {
      type: String,
      default: 'black',
    },
    propertyName: String,
  },
  setup (props) {
    const localCentileData = computed(() => {
      var result = {}
      if (props.centileData) {
        for (var centile of ['p03', 'p50', 'p97']) {
          result[centile] = props.centileData.map((c) => {
            return { x: c.age, y: c[centile] }
          })
        }
      }
      return result
    })

    return {
      chartData: computed(() => {
        return {
          datasets: [
            {
              label: props.propertyName,
              type: 'scatter',
              data: props.scatterData,
              backgroundColor: props.color,
            },
            {
              label: 'p03',
              type: 'line',
              fill: false,
              borderWidth: 2,
              data: localCentileData.value.p03,
              borderColor: 'black',
              pointRadius: 0,
              pointHitRadius: 0,
            },
            {
              label: 'p50',
              type: 'line',
              fill: false,
              borderDash: [5],
              borderWidth: 2,
              data: localCentileData.value.p50,
              borderColor: 'black',
              pointRadius: 0,
              pointHitRadius: 0,
            },
            {
              label: 'p97',
              type: 'line',
              fill: false,
              borderWidth: 2,
              data: localCentileData.value.p97,
              borderColor: 'black',
              pointRadius: 0,
              pointHitRadius: 0,
            },
          ],
        }
      })
    }
  }
})
</script>
